#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /config

# copy default config file example
rm -f /config/config.example.toml
cp /defaults/config.example.toml /config/config.example.toml

# copy default config file if it doesn't exist
if [[ ! -f /config/config.toml ]]; then
    cp /defaults/config.example.toml /config/config.toml
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # permissions
    lsiown -R abc:abc \
        /config
fi
